trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path
from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create_employee/', views.create_employee, name="create_employee"),
    path('edit_employee_profile/', views.edit_employee_profile, name="edit_employee_profile"),
    path('confirm_pickup/', views.confirm_pickup, name="confirm_pickup")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=5)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.db.models.manager import EmptyManager
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Employee
from django.core.exceptions import ObjectDoesNotExist
from datetime import date
from django.views import generic
from django.shortcuts import get_object_or_404
# Create your views here.
# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

@login_required
def index(request):
    logged_in_user = request.user
    Customer = apps.get_model('customers.Customer')
    try: 
        logged_in_employee = Employee.objects.get(user=logged_in_user)
        today = date.today()
        weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        weekday_num = today.weekday()
        specific_day = weekdays[weekday_num]
        
        
      
        customers_in_zipcode = Customer.objects.filter(zip_code=logged_in_employee.zip_code)
        todays_customer_pickup = customers_in_zipcode.filter(one_time_pickup=today) | customers_in_zipcode.filter(weekly_pickup=specific_day)
        non_suspended_accounts = todays_customer_pickup.exclude(suspend_start__lte=today, suspend_end__gte=today)
        non_picked_up_trash = non_suspended_accounts.exclude(date_of_last_pickup=today)
        
        

        context = {
            'logged_in_employee': logged_in_employee,
            'today' : today,
            'non_picked_up_trash' : non_picked_up_trash,
            'specific_day' : specific_day,
            
    }
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create_employee'))
    
    
@login_required
def create_employee(request):
    logged_in_user = request.user
    if request.method == "POST":
        name = request.POST.get('name')
        zip_code = request.POST.get('zip_code')
        new_employee = Employee(name=name, zip_code=zip_code, user=logged_in_user)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create_employee.html')

@login_required
def edit_employee_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.name = name_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_employee.html', context)

@login_required
def confirm_pickup(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.filter(user=logged_in_user)
    logged_in_employee.save()
    return render(request, 'employees/confirm.html')

trash_collector/employees/templates/employees/confirm.html
{% extends 'base.html' %}

{% block title %} Confirm Pickup {% endblock %}

{% block header %} Pickup Confirmed! {% endblock %}

<form action="{% url 'employees:confirm_pickup' %}" method="post">
</form>

trash_collector/employees/templates/employees/create_employee.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create_employee' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_employee.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />

<form action="{% url 'employees:edit_employee_profile' %}" method="post">
    {% csrf_token %}
    Name: <input type="name" name="name" id="name"><br />
    Zip Code: <input type="zip_code" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_employee_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
        Hello Employee {{ logged_in_employee.name }}!
        Zip Code: {{logged_in_employee.zip_code }}<br />
        <div> Customers in Zip Code Who Need Service Today {{non_picked_up_trash}}  <a href="{% url 'employees:confirm_pickup' %}"> Confirm Pickup</a> 
        </div>
        <div> Pick Up Day : {{specific_day}}

        

    
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}